//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class Products
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Creator { get; set; }
        public double Price { get; set; }
        public int Sale { get; set; }
        public string Picture { get; set; }

        public string PriceText
        {
            get
            {
                if (this.Sale > 0)
                {
                    string str = this.Price.ToString();
                    float? newPrice = (float?)(this.Price - (this.Price * this.Sale / 100));
                    string through = "";
                    foreach (char c in str)
                    {
                        through += c + "\u0336";
                    }
                    //through.Add(TextDecorations.Strikethrough);
                    return ("Старая цена:\n" + through + "\nЦена:\n" + newPrice + "р.");
                }
                else
                {
                    return "Цена:\n" + this.Sale + "р.";
                }
            }
        }
        public string Image
        {
            get
            {
                if (this.Picture == null)
                {

                    return (Environment.CurrentDirectory + "\\images\\unknown.png");
                }
                else
                {
                    return (Environment.CurrentDirectory + "\\images\\" + this.Picture);
                }
            }
        }
        public SolidColorBrush solidColorBrush
        {
            get
            {
                if (this.Sale >= 15)
                {
                    SolidColorBrush brush = (SolidColorBrush)(new BrushConverter().ConvertFrom("#7fff00"));
                    return brush;
                }
                else
                {
                    return Brushes.Transparent;
                }
            }
        }
    }
}
